# Generated by Django 3.2 on 2025-05-06 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0029_auto_20250403_1442'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='related_order',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 5, 16, 12, 42, 143006)),
        ),
        migrations.CreateModel(
            name='Coupon_first',
            fields=[
                ('coupon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.coupon')),
                ('related_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ccheckout.order')),
            ],
            bases=('payments.coupon',),
        ),
    ]
