# Generated by Django 3.2 on 2025-05-06 19:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0030_auto_20250506_1921'),
        ('payments', '0002_auto_20250506_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applied_to_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_coupon', to='ccheckout.order'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 5, 19, 21, 7, 912507)),
        ),
    ]
