# Generated by Django 3.2 on 2025-06-03 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0031_auto_20250603_1307'),
        ('payments', '0003_auto_20250506_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='applied_to_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_coupon', to='ccheckout.order', verbose_name='Orden a la que se le aplica el cupón'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 3, 13, 6, 59, 617045)),
        ),
        migrations.AlterField(
            model_name='coupon_first',
            name='related_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ccheckout.order', verbose_name='Orden que genera el cupón'),
        ),
    ]
