"""
Django settings for tienda project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ
import json

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

#SECRET_KEY = 'django-insecure-%s)n3v*q7f0jgnt3taoo#=eeuepers8ep38&5gh#&i#t+41rne'
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False
DEBUG = env('DEBUG', cast=bool)

ALLOWED_HOSTS = env('ALLOWED_HOSTS', cast=list) 
#ALLOWED_HOSTS = ['tienda.produccionesmuhia.ca']

FIRST_PURCHASE_DISCOUNT = 10
COUPON_EXPIRATION_DAYS = 30

""" CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Havana_City'  # Ajustar a tu zona horaria
CELERY_ENABLE_UTC = True """


LOGOUT_REDIRECT_URL = '/'
#LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# Configuracion de correo
#EMAIL_SETTINGS_FILE = os.path.join(BASE_DIR, 'tienda/email_settings.json') with open(EMAIL_SETTINGS_FILE) as data_file:
#    email_settings = json.load(data_file)

#EMAIL_HOST = env('EMAIL_HOST')
#EMAIL_PORT = env('EMAIL_PORT')
#EMAIL_HOST_USER = env('EMAIL_HOST_USER')
#EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
#EMAIL_USE_TLS = env('EMAIL_USE_TLS')


#EMAIL_HOST = 'produccionesmuhia.ca'
#EMAIL_HOST_USER = 'ycoca@produccionesmuhia.ca'
#EMAIL_HOST_PASSWORD = 'TestingCorreo2024++'
#EMAIL_PORT =  '465'
#MAIL_USE_TLS = True
#EMAIL_USE_SSL = False

""" EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'ycocab@gmail.com'
EMAIL_RECEIPT = 'ycoca@produccionesmuhia.ca'
EMAIL_HOST_PASSWORD = 'zccvswdhcvtoblpm'
EMAIL_PORT =  '587'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False """

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'produccionesmuhia.ca'
EMAIL_HOST_USER = 'ycoca@produccionesmuhia.ca'
EMAIL_RECEIPT = 'ycoca@produccionesmuhia.ca'
EMAIL_HOST_PASSWORD = 'TestingCorreo2024++'
EMAIL_PORT =  '465'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True 
ACCOUNT_ACTIVATION_DAYS = 7
SERVER_EMAIL = 'ycoca@produccionesmuhia.ca'

EMAIL_TIMEOUT = 10
EMAIL_SUBJECT_PREFIX = '[Producciones MUHIA]'

#EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
#EMAIL_HOST_USER = '136a9ea75e0faf'
#EMAIL_HOST_PASSWORD = '72fb00b192a4f6'
#EMAIL_PORT =  '25'

# Application definition

INSTALLED_APPS = [
    'registration.apps.RegistrationConfig',
    #apps predefinidas
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'widget_tweaks',
    
    #apps modulos del sistema
    'cart.apps.CartConfig',
    'catalog.apps.CatalogConfig',
    'ccheckout.apps.CcheckoutConfig',
    'pages.apps.PagesConfig',
    'contact.apps.ContactConfig',
    'stores.apps.StoresConfig',
    'utils.apps.UtilsConfig',
    'promo.apps.PromoConfig',
    'services.apps.ServicesConfig',
    'wallet.apps.WalletConfig',
    'notification.apps.NotificationConfig',
    'tienda',

    #apps adicionales
    'bootstrap5',
    'django_ckeditor_5',
    #'psycopg',
    #'allauth',
    #'allauth.account',
    #'allauth.socialaccount',
]

#configuracion básica del ckeditors
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH = "/media/ckeditor/"

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


#¿?
#NPM_BIN_PATH =

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    #'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 2

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    #'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'tienda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'utils.context_processors.tienda_generales',
            ],
        },
    },
]

WSGI_APPLICATION = 'tienda.wsgi.app'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'zcipcnjx_tienda',
#        'USER': 'zcipcnjx_postgres',
#        'PASSWORD': 'BaseDatos2024++',
#        'HOST': '127.0.0.200',
#        'PORT': 5432,
#    }
#}

#Configuracion POSTGRES


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"

# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
        'wallet_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'wallet.log'),
            'formatter': 'simple',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'wallet': {
            'handlers': ['wallet_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'tienda': {  # Reemplaza 'tu_app' con el nombre de tu aplicación
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Crear directorio de logs si no existe
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

    
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

MEDIA_URL = '/media/'
#MEDIA_ROOT = #'/home/zcipcnjx/tiendaMuhia/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

CSRF_TRUSTED_ORIGINS = ["127.0.0.1:8000"]

SESSION_COOKIE_NAME = 'sessionid'

SESSION_COOKIE_HTTPONLY = True

SESSION_COOKIE_SECURE = True

if DEBUG:
    SESSION_COOKIE_SECURE = False

customColorPalette = [
        {
            'color': 'hsl(4, 90%, 58%)',
            'label': 'Red'
        },
        {
            'color': 'hsl(340, 82%, 52%)',
            'label': 'Pink'
        },
        {
            'color': 'hsl(291, 64%, 42%)',
            'label': 'Purple'
        },
        {
            'color': 'hsl(262, 52%, 47%)',
            'label': 'Deep Purple'
        },
        {
            'color': 'hsl(231, 48%, 48%)',
            'label': 'Indigo'
        },
        {
            'color': 'hsl(207, 90%, 54%)',
            'label': 'Blue'
        },
    ]
CKEDITOR_5_CUSTOM_CSS = 'path_to.css' # optional
""" CKEDITOR_5_FILE_STORAGE = "path_to_storage.CustomStorage" # optional """
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
        'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable',],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_NAME = 'Tienda MUHIA'
SITE_URL = 'https://tienda.produccionesmuhia.ca'
SUPPORT_EMAIL = 'muhia@produccionesmuhia.ca'
META_KEYWORDS = 'aseo, limpieza, detergente, champú, muhia, carro, auto'
META_DESCRIPTION = 'La tienda virtual MUHIA le ofrece venta de productos de aseo, limpieza para el hogar y su auto.'

