# Generated by Django 3.2 on 2025-06-23 18:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_product_is_summary_product'),
        ('utils', '0004_price_min_delivery_free'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0018_auto_20250428_2216'),
        ('ccheckout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Orden de compra'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_zip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_zip',
        ),
        migrations.AddField(
            model_name='order',
            name='base_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total base'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Porciento de descuento de cupón'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Tipo de moneda'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Tipo de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address_2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección alternativa'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_apto',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='Número/Apartamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_between',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='Entre calles'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_ci',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Número de identidad'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del beneficiario'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='Precio de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_state',
            field=models.CharField(default='La Habana', max_length=50, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_street',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_substate',
            field=models.IntegerField(choices=[(0, 'Guanabacoa'), (1, 'La Habana del Este'), (2, 'Cerro'), (3, 'Cotorro'), (4, 'Diez de Octubre'), (5, 'La Habana Vieja'), (6, 'Centro Habana'), (7, 'San Miguel del Padrón'), (8, 'Boyeros'), (9, 'Marianao'), (10, 'La Lisa'), (11, 'Plaza de la Revolución'), (12, 'Playa'), (13, 'Regla'), (14, 'Arroyo Naranjo')], default=0, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_ws',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono WhatsApp'),
        ),
        migrations.AddField(
            model_name='order',
            name='end_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total final con descuento y envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_daily_summary',
            field=models.BooleanField(default=False, verbose_name='Es resumen diario'),
        ),
        migrations.AddField(
            model_name='order',
            name='others_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Porciento de otros descuentos'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_url',
            field=models.URLField(default='', verbose_name='URL de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_city',
            field=models.CharField(blank=True, default=None, help_text='Ciudad del banco de la tarjeta', max_length=20, null=True, verbose_name='Ciudad del banco'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_details',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalles de la compra'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_email',
            field=models.EmailField(blank=True, default=None, max_length=50, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del titular'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono móvil'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_postCode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.price', verbose_name='Valores para el cálculo del Precio de la compra'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_sumary', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='order',
            name='store_name',
            field=models.CharField(default='Envío Habana', max_length=200, verbose_name='Nombre del tipo de entrega'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_summary_item',
            field=models.BooleanField(default=False, verbose_name='Elemento especial de resumen diario '),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='store_name',
            field=models.CharField(default='Envío Habana', max_length=250, verbose_name='Forma de entrega'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='totalf',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=9, verbose_name='Precio total del producto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de facturación'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='Dirección ip'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Solicitada'), (1, 'Procesada'), (2, 'Pagada'), (3, 'Transportando'), (4, 'Cancelada'), (5, 'Entregada'), (6, 'Devuelta'), (7, 'Confirmada')], default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(help_text='No. de transacción', max_length=20, verbose_name='Nro. Transacción'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ccheckout.order', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=9, verbose_name='Cantidad'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('CARD', 'Tarjeta')], max_length=20, verbose_name='Métodos de pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('transaction_count', models.PositiveIntegerField(default=1, verbose_name='Cantidad de transacciones')),
                ('transaction_details', models.TextField(blank=True, null=True, verbose_name='Detalles')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='ccheckout.order')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=10)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2025, 7, 23, 18, 10, 41, 866329))),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_to_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_coupon', to='ccheckout.order', verbose_name='Orden a la que se le aplica el cupón')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='ccheckout.coupon', verbose_name='Cupón de descuento'),
        ),
        migrations.CreateModel(
            name='Coupon_first',
            fields=[
                ('coupon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ccheckout.coupon')),
                ('related_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ccheckout.order', verbose_name='Orden que genera el cupón')),
            ],
            bases=('ccheckout.coupon',),
        ),
    ]
