# Generated by Django 3.2 on 2025-06-30 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0002_auto_20250623_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 12, 23, 32, 76881)),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='URL de pago'),
        ),
    ]
