# Generated by Django 3.2 on 2025-07-07 02:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccheckout', '0003_auto_20250630_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_reported',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total reportado'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.PositiveIntegerField(default=10, verbose_name='Descuento (%)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 2, 6, 31, 180716), verbose_name='Expira'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Usado'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
