# Generated by Django 3.2 on 2025-07-23 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0004_auto_20250707_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cup_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total en CUP'),
        ),
        migrations.AddField(
            model_name='order',
            name='mlc_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total en MLC'),
        ),
        migrations.AddField(
            model_name='order',
            name='usd_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total en USD'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 2, 39, 0, 999732), verbose_name='Expira'),
        ),
    ]
