# Generated by Django 3.2 on 2025-09-06 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0005_auto_20250723_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vale_salida',
            field=models.CharField(blank=True, help_text='Vale salida almacén', max_length=20, null=True, verbose_name='Vale almacén'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 6, 2, 36, 45, 533796), verbose_name='Expira'),
        ),
    ]
