# Generated by Django 3.2 on 2025-09-11 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0006_auto_20250906_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 11, 19, 15, 56, 928739), verbose_name='Expira'),
        ),
    ]
