# Generated by Django 3.2 on 2025-09-12 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0007_auto_20250911_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 12, 18, 0, 50, 493009), verbose_name='Expira'),
        ),
    ]
