# Generated by Django 3.2 on 2025-09-14 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0008_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 14, 3, 13, 5, 311814), verbose_name='Expira'),
        ),
    ]
