# Generated by Django 3.2 on 2025-11-27 21:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='registration.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Incentivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del incentivo', max_length=200)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, help_text='Monto que el cliente debe alcanzar para obtener el incentivo', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('umbral_notificacion', models.DecimalField(decimal_places=2, help_text='Monto a partir del cual se notifica al cliente sobre el incentivo cercano', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto_incentivo', models.ForeignKey(help_text='Producto a otorgar como incentivo', on_delete=django.db.models.deletion.CASCADE, related_name='incentivos', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Incentivo',
                'verbose_name_plural': 'Incentivos',
                'ordering': ['monto_objetivo'],
            },
        ),
        migrations.CreateModel(
            name='ClienteIncentivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notificado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('notificado', 'Notificado'), ('completado', 'Completado'), ('expirado', 'Expirado'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incentivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.incentivo')),
            ],
            options={
                'verbose_name': 'Incentivo de Cliente',
                'verbose_name_plural': 'Incentivos de Clientes',
                'unique_together': {('cliente', 'incentivo')},
            },
        ),
    ]
