# Generated by Django 3.2 on 2025-10-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_clienteincentivo_incentivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteincentivo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('notificado', 'Notificado'), ('completado', 'Completado'), ('expirado', 'Expirado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
