# Generated by Django 3.2 on 2025-04-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccheckout', '0028_auto_20241123_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del titular'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono móvil'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=9, verbose_name='Cantidad'),
        ),
    ]
