from django.urls import path, re_path
from . import views

urlpatterns = [
    path("", views.show_checkout, name='checkout'),
    path("pagar/", views.pagar, name='pagar'),
    path("facturar/", views.facturar, name='facturar'),
    path("reservar/", views.reserve, name='reservar'),
    path("transfer/", views.transfer, name='transfer'), 
    path("efectivo/", views.cach, name='efectivo'),    
    path("resumen/<order_id>/", views.download_daily_summary_pdf, name='resumen_pdf'),
    path("recibo/", views.receipt, name='checkout_receipt'),
    path("procesado/<order_id>/", views.confirmado, name='checkout_procesado'),
    path('pdf/', views.export_pdf, name='export_pdf'),
    path("fallo/", views.fail, name='checkout_fail'),
    path("exito/", views.hit, name='checkout_hit'),
    path("compras/", views.orders_list, name='orders_list'),
    path("compras/<order_id>/", views.details, name='details'),
    path("transfer/<order_id>/", views.transfer_pay, name='transfer_pay'),
    path("notification/", views.payment_notification, name='notification'),
    path("gestion/", views.admin_orders_list, name='admin_orders_list'),
    path("compras-clientes/", views.clients_orders_list, name='clients_orders_list'),
    path("actualiza_orden/", views.vendedor_orders_list, name='vendedor_orders_list'),
    path("resumen_diario/", views.create_daily_summary, name='resumen'),
    path('venta-productos/', views.sales_products, name='venta_productos'),
    path('venta-clientes/', views.sales_client, name='venta_clientes'),
    path('venta-resumen/', views.sales_summary, name='venta_resumen'),
    path('ventas-totales-resumen/', views.sales_total_summary, name='ventas_totales_resumen'),
    path('resumen_oficial/', views.summary_oficial_sales, name='sales_oficial_summary'),
    path('ventas/', views.sales_manages, name='ventas'),
    path('ordenes/', views.ordenes, name='ordenes'),
    path('configuraciones/', views.configurations, name='configuraciones'),
    path('marketing/', views.marketing, name='marketing'),
    path('cupones/crear', views.Crear_cupones.as_view(template_name="checkout/cupon_create.html"), name='crear_cupon'),
    path('cupones/', views.Gestion_cupones.as_view(template_name="checkout/cupon_list.html"), name='cupones'),
    path('cupones/<uuid:code>/editar/', views.Update_cupones.as_view(template_name="checkout/cupon_update.html"), name = 'update_cupon'),
    path('cupones/eliminar/<uuid:code>', views.eliminar_cupon, name = 'eliminar_cupon'),
]
