# Generated by Django 4.2 on 2025-12-26 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10, null='True', verbose_name='Teléfono (Con WhatsApp)')),
                ('correo', models.CharField(max_length=50, null='True', verbose_name='Correo electrónico')),
                ('carnet', models.CharField(max_length=11)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('encurso', 'En curso'), ('pagado', 'Pagado'), ('recibido', 'Recibido')], default='pendiente', max_length=20)),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de servicios',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
