# Generated by Django 3.2 on 2025-04-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='correo',
            field=models.CharField(max_length=50, null='True', verbose_name='Correo electrónico'),
        ),
    ]
