# Generated by Django 3.2 on 2025-04-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_solicitud_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
