# Generated by Django 3.2 on 2025-04-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_solicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default='', max_length=20),
        ),
    ]
