# Generated by Django 3.2 on 2025-04-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name_plural': 'Solicitudes de servicios'},
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='servicios',
            new_name='servicio',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('encurso', 'En curso'), ('pagado', 'Pagado'), ('recibido', 'Recibido')], default='pendiente', max_length=20),
        ),
    ]
