# Generated by Django 3.2 on 2025-04-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20250404_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='servicio',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicio'),
        ),
    ]
