# Generated by Django 3.2 on 2025-10-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_at'], 'verbose_name': 'Transaccion', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['user'], 'verbose_name': 'Monedero', 'verbose_name_plural': 'Monederos'},
        ),
    ]
